services:
  nginx:
    build: .
    container_name: nginx-container
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
